"""SLA113 Game Template Library — Genre-specific PixiJS starter code generators."""
import json


def get_game_template(game_type, game_name, game_config, asset_manifest):
    """Return genre-specific PixiJS game code for the given game type."""
    config_json = json.dumps(game_config, default=str, indent=2)
    manifest_json = json.dumps(asset_manifest, default=str, indent=2)

    templates = {
        "fish_shooting": _fish_shooting_template,
        "slot_machine": _slot_machine_template,
        "video_poker": _video_poker_template,
        "casino_suite": _slot_machine_template,
        "pachinko": _slot_machine_template,
        "card_games": _video_poker_template,
        "tactical_fps": _tactical_fps_template,
        "cod_warfare": _tactical_fps_template,
        "battle_royale": _tactical_fps_template,
        "open_world": _open_world_template,
        "fantasy_rpg": _rpg_template,
        "open_world_rpg": _rpg_template,
        "dungeon_crawler": _rpg_template,
        "cyberpunk": _rpg_template,
        "platformer": _platformer_template,
        "racing_sim": _racing_template,
        "horror": _horror_template,
        "fighting": _fighting_template,
        "puzzle": _puzzle_template,
    }

    generator = templates.get(game_type, _default_template)
    return generator(game_name, game_type, config_json, manifest_json, asset_manifest)


def _header(game_name, game_type, config_json, manifest_json):
    return (
        f"// SLA113 Game Engine — {game_name}\n"
        f"// Template: {game_type.replace('_', ' ').title()}\n"
        f"// Auto-generated by SLA113 Build Pipeline\n\n"
        f"const GAME_CONFIG = {config_json};\n"
        f"const ASSET_MANIFEST = {manifest_json};\n\n"
    )


def _fish_shooting_template(game_name, game_type, config_json, manifest_json, assets):
    return _header(game_name, game_type, config_json, manifest_json) + """(async () => {
  const app = new PIXI.Application({ width: window.innerWidth, height: window.innerHeight, backgroundColor: 0x001020, antialias: true });
  document.body.appendChild(app.view);
  document.getElementById('loading').style.display = 'none';
  window.addEventListener('resize', () => app.renderer.resize(window.innerWidth, window.innerHeight));

  const W = app.screen.width, H = app.screen.height;
  let score = 0, ammo = 100, credits = 1000;

  // Ocean background with gradient
  const bg = new PIXI.Graphics();
  bg.beginFill(0x001830).drawRect(0, 0, W, H).endFill();
  for (let y = 0; y < H; y += 3) {
    bg.lineStyle(1, 0x002040 + Math.floor(y/H * 0x30));
    bg.moveTo(0, y).lineTo(W, y);
  }
  app.stage.addChild(bg);

  // Bubbles
  const bubbles = [];
  for (let i = 0; i < 30; i++) {
    const b = new PIXI.Graphics();
    b.beginFill(0x00c8ff, 0.15).drawCircle(0, 0, 2 + Math.random() * 6).endFill();
    b.x = Math.random() * W; b.y = Math.random() * H;
    b.vy = -0.3 - Math.random() * 0.5;
    b.vx = (Math.random() - 0.5) * 0.3;
    app.stage.addChild(b); bubbles.push(b);
  }

  // Fish entities
  const fishColors = [0xff6600, 0xd4af37, 0x00c8ff, 0xff4444, 0x44ff44, 0x9966ff, 0xff00ff];
  const fishValues = [10, 25, 50, 100, 200, 500, 1000];
  const fish = [];

  function spawnFish() {
    const tier = Math.floor(Math.random() * fishColors.length);
    const g = new PIXI.Graphics();
    const size = 15 + tier * 5;
    g.beginFill(fishColors[tier], 0.9);
    g.moveTo(size, 0).lineTo(-size, -size*0.6).lineTo(-size*0.5, 0).lineTo(-size, size*0.6).closePath();
    g.endFill();
    // Eye
    g.beginFill(0xffffff).drawCircle(size*0.4, -size*0.15, 3).endFill();
    g.beginFill(0x000000).drawCircle(size*0.5, -size*0.15, 1.5).endFill();

    const fromLeft = Math.random() > 0.5;
    g.x = fromLeft ? -40 : W + 40;
    g.y = 80 + Math.random() * (H - 180);
    g.vx = (fromLeft ? 1 : -1) * (0.5 + Math.random() * (1 + tier * 0.3));
    g.vy = (Math.random() - 0.5) * 0.5;
    g.scale.x = fromLeft ? 1 : -1;
    g.tier = tier; g.hp = 1 + tier; g.value = fishValues[tier];
    g.interactive = true; g.cursor = 'crosshair';
    g.on('pointerdown', () => {
      if (ammo <= 0) return;
      ammo--;
      g.hp--;
      g.alpha = 0.5; setTimeout(() => { g.alpha = g.hp > 0 ? 0.9 : 0; }, 100);
      if (g.hp <= 0) {
        score += g.value; credits += g.value;
        document.getElementById('score').textContent = credits;
        // Explosion
        for (let p = 0; p < 8; p++) {
          const particle = new PIXI.Graphics();
          particle.beginFill(fishColors[tier]).drawCircle(0,0,2).endFill();
          particle.x = g.x; particle.y = g.y;
          particle.vx = (Math.random()-0.5)*5; particle.vy = (Math.random()-0.5)*5;
          particle.life = 30; app.stage.addChild(particle); bubbles.push(particle);
        }
        g.x = -999;
      }
    });
    app.stage.addChild(g); fish.push(g);
  }

  for (let i = 0; i < 12; i++) spawnFish();
  setInterval(spawnFish, 2000);
  setInterval(() => { ammo = Math.min(ammo + 5, 100); }, 1000);

  // Crosshair
  const crosshair = new PIXI.Graphics();
  crosshair.lineStyle(1, 0xff0000, 0.8);
  crosshair.drawCircle(0,0,15).moveTo(-20,0).lineTo(20,0).moveTo(0,-20).lineTo(0,20);
  crosshair.zIndex = 1000; app.stage.addChild(crosshair);
  app.stage.sortableChildren = true;
  app.view.addEventListener('mousemove', e => { crosshair.x = e.offsetX; crosshair.y = e.offsetY; });

  // HUD update
  const hudAmmo = document.createElement('div');
  hudAmmo.style.cssText = 'position:fixed;bottom:16px;left:16px;color:#00c8ff;font:11px monospace;text-transform:uppercase;letter-spacing:2px;z-index:100';
  document.body.appendChild(hudAmmo);

  app.ticker.add(() => {
    fish.forEach(f => {
      f.x += f.vx; f.y += f.vy + Math.sin(Date.now()/500 + f.x) * 0.3;
      if (f.x < -80 || f.x > W+80) { f.x = f.vx > 0 ? -40 : W+40; f.y = 80+Math.random()*(H-180); }
    });
    bubbles.forEach(b => {
      if (b.life !== undefined) { b.x += b.vx; b.y += b.vy; b.life--; b.alpha = b.life/30; if(b.life<=0) b.visible=false; }
      else { b.x += b.vx; b.y += b.vy; if(b.y < -10) { b.y = H+10; b.x = Math.random()*W; } }
    });
    hudAmmo.textContent = `AMMO: ${ammo} | CREDITS: ${credits} | KILLS: ${score}`;
  });

  console.log('[SLA113] Fish Shooting initialized');
})();
"""


def _slot_machine_template(game_name, game_type, config_json, manifest_json, assets):
    return _header(game_name, game_type, config_json, manifest_json) + """(async () => {
  const app = new PIXI.Application({ width: window.innerWidth, height: window.innerHeight, backgroundColor: 0x0a0008, antialias: true });
  document.body.appendChild(app.view);
  document.getElementById('loading').style.display = 'none';
  window.addEventListener('resize', () => app.renderer.resize(window.innerWidth, window.innerHeight));

  const W = app.screen.width, H = app.screen.height;
  let credits = 10000, bet = 100, spinning = false;
  const symbols = ['7', 'BAR', 'CHERRY', 'BELL', 'LEMON', 'STAR', 'DIAMOND'];
  const symColors = [0xff0000, 0xd4af37, 0xff4444, 0xffcc00, 0x44ff44, 0x00c8ff, 0xff66ff];
  const payouts = { '777': 50, 'BARBARBAR': 20, 'CHERRYCHERRYCHERRY': 10, 'BELLBELLBELL': 8, 'STARSTARSTAR': 15, 'DIAMONDDIAMONDDIAMON': 25 };

  // Machine frame
  const frame = new PIXI.Graphics();
  frame.lineStyle(3, 0xd4af37);
  const mx = W/2-200, my = H/2-120;
  frame.drawRoundedRect(mx, my, 400, 240, 8);
  frame.beginFill(0x0a0008).drawRoundedRect(mx+10, my+10, 380, 220, 4).endFill();
  // Reel dividers
  frame.lineStyle(1, 0x333333);
  frame.moveTo(mx+137, my+10).lineTo(mx+137, my+230);
  frame.moveTo(mx+263, my+10).lineTo(mx+263, my+230);
  app.stage.addChild(frame);

  // Reels
  const reels = [[], [], []];
  const reelContainers = [];
  for (let r = 0; r < 3; r++) {
    const container = new PIXI.Container();
    container.x = mx + 15 + r * 127; container.y = my + 15;
    const mask = new PIXI.Graphics();
    mask.beginFill(0xffffff).drawRect(0, 0, 120, 210).endFill();
    mask.x = container.x; mask.y = container.y;
    app.stage.addChild(mask);
    container.mask = mask;
    // Create symbol tiles
    for (let i = 0; i < 15; i++) {
      const idx = i % symbols.length;
      const txt = new PIXI.Text(symbols[idx], { fontSize: 28, fill: symColors[idx], fontFamily: 'monospace', fontWeight: 'bold' });
      txt.anchor.set(0.5); txt.x = 60; txt.y = i * 70 + 35;
      txt.symIdx = idx;
      container.addChild(txt); reels[r].push(txt);
    }
    app.stage.addChild(container); reelContainers.push(container);
  }

  const resultSymbols = [0, 0, 0];
  let reelSpeeds = [0, 0, 0];
  let reelTargets = [null, null, null];

  function spin() {
    if (spinning || credits < bet) return;
    spinning = true; credits -= bet;
    document.getElementById('score').textContent = credits;
    // Determine results
    const lucky = Math.random();
    if (lucky < 0.05) { resultSymbols[0] = resultSymbols[1] = resultSymbols[2] = 0; } // 777
    else if (lucky < 0.15) { const s = Math.floor(Math.random()*symbols.length); resultSymbols[0]=resultSymbols[1]=resultSymbols[2]=s; }
    else { for(let i=0;i<3;i++) resultSymbols[i] = Math.floor(Math.random()*symbols.length); }

    reelSpeeds = [15 + Math.random()*5, 15 + Math.random()*5, 15 + Math.random()*5];
    reelTargets = [null, null, null];
    setTimeout(() => reelTargets[0] = resultSymbols[0], 800);
    setTimeout(() => reelTargets[1] = resultSymbols[1], 1400);
    setTimeout(() => reelTargets[2] = resultSymbols[2], 2000);
  }

  // Spin button
  const spinBtn = new PIXI.Graphics();
  spinBtn.beginFill(0xd4af37).drawRoundedRect(0,0,200,50,6).endFill();
  const spinTxt = new PIXI.Text('SPIN', { fontSize: 20, fill: 0x000000, fontFamily: 'monospace', fontWeight: 'bold' });
  spinTxt.anchor.set(0.5); spinTxt.x = 100; spinTxt.y = 25;
  spinBtn.addChild(spinTxt);
  spinBtn.x = W/2-100; spinBtn.y = my + 260;
  spinBtn.interactive = true; spinBtn.cursor = 'pointer';
  spinBtn.on('pointerdown', spin);
  app.stage.addChild(spinBtn);

  // Bet controls
  const betTxt = new PIXI.Text('BET: 100', { fontSize: 12, fill: 0xd4af37, fontFamily: 'monospace' });
  betTxt.x = W/2-100; betTxt.y = my + 320; app.stage.addChild(betTxt);

  app.ticker.add(() => {
    for (let r = 0; r < 3; r++) {
      if (reelSpeeds[r] > 0) {
        reelContainers[r].children.forEach(txt => {
          txt.y += reelSpeeds[r];
          if (txt.y > 15 * 70) txt.y -= 15 * 70;
        });
        if (reelTargets[r] !== null) {
          reelSpeeds[r] *= 0.95;
          if (reelSpeeds[r] < 0.5) {
            reelSpeeds[r] = 0;
            // Snap to result
            reelContainers[r].children.forEach((txt, i) => { txt.y = i * 70 + 35; });
            if (r === 2 && reelSpeeds.every(s => s === 0)) {
              // Check win
              const combo = resultSymbols.map(i => symbols[i]).join('');
              const allSame = resultSymbols[0] === resultSymbols[1] && resultSymbols[1] === resultSymbols[2];
              if (allSame) {
                const mult = resultSymbols[0] === 0 ? 50 : resultSymbols[0] === 6 ? 25 : 10;
                credits += bet * mult;
                document.getElementById('score').textContent = credits;
              }
              spinning = false;
            }
          }
        }
      }
    }
  });

  // Keyboard spin
  document.addEventListener('keydown', e => { if(e.code === 'Space') spin(); });
  console.log('[SLA113] Slot Machine initialized');
})();
"""


def _tactical_fps_template(game_name, game_type, config_json, manifest_json, assets):
    return _header(game_name, game_type, config_json, manifest_json) + """(async () => {
  const app = new PIXI.Application({ width: window.innerWidth, height: window.innerHeight, backgroundColor: 0x0a0a0a, antialias: true });
  document.body.appendChild(app.view);
  document.getElementById('loading').style.display = 'none';
  window.addEventListener('resize', () => app.renderer.resize(window.innerWidth, window.innerHeight));

  const W = app.screen.width, H = app.screen.height;
  let score = 0, hp = 100, ammo = 30, kills = 0, wave = 1;
  const keys = {};
  document.addEventListener('keydown', e => keys[e.code] = true);
  document.addEventListener('keyup', e => keys[e.code] = false);

  // Ground plane
  const ground = new PIXI.Graphics();
  ground.beginFill(0x1a1a1a).drawRect(0, H*0.6, W, H*0.4).endFill();
  for (let x = 0; x < W; x += 60) { ground.lineStyle(1, 0x222222).moveTo(x, H*0.6).lineTo(x, H); }
  app.stage.addChild(ground);

  // Player
  const player = new PIXI.Graphics();
  player.beginFill(0x00c8ff).drawRect(-12, -20, 24, 40).endFill();
  player.beginFill(0x008899).drawRect(-8, -30, 16, 12).endFill(); // head
  player.beginFill(0xd4af37).drawRect(10, -8, 20, 4).endFill(); // gun
  player.x = W/2; player.y = H*0.75;
  app.stage.addChild(player);

  // Enemies
  const enemies = [];
  function spawnEnemy() {
    const e = new PIXI.Graphics();
    e.beginFill(0xff4444).drawRect(-10, -16, 20, 32).endFill();
    e.beginFill(0xcc0000).drawRect(-6, -24, 12, 10).endFill();
    e.x = Math.random() > 0.5 ? -20 : W+20;
    e.y = H*0.6 + 20 + Math.random()*80;
    e.vx = (e.x < 0 ? 1 : -1) * (0.5 + wave * 0.2 + Math.random());
    e.hp = 1 + Math.floor(wave/3);
    e.interactive = true; e.cursor = 'crosshair';
    app.stage.addChild(e); enemies.push(e);
  }

  // Bullets
  const bullets = [];
  function shoot() {
    if (ammo <= 0) return;
    ammo--;
    const b = new PIXI.Graphics();
    b.beginFill(0xd4af37).drawRect(-2, -4, 4, 8).endFill();
    b.x = player.x + 20; b.y = player.y - 8;
    b.vy = -8;
    app.stage.addChild(b); bullets.push(b);
  }

  document.addEventListener('keydown', e => { if(e.code === 'Space') shoot(); });
  app.view.addEventListener('click', shoot);

  setInterval(spawnEnemy, 2000 / Math.max(1, wave * 0.5));
  setInterval(() => { ammo = Math.min(ammo + 5, 30); }, 2000);
  setInterval(() => { wave++; }, 15000);

  // Crosshair
  const cross = new PIXI.Graphics();
  cross.lineStyle(1, 0x00c8ff, 0.6).drawCircle(0,0,12).moveTo(-16,0).lineTo(16,0).moveTo(0,-16).lineTo(0,16);
  cross.zIndex = 999; app.stage.addChild(cross);
  app.stage.sortableChildren = true;
  app.view.addEventListener('mousemove', e => { cross.x = e.offsetX; cross.y = e.offsetY; });

  const hud = document.createElement('div');
  hud.style.cssText = 'position:fixed;bottom:16px;right:16px;color:#00c8ff;font:11px monospace;text-transform:uppercase;letter-spacing:2px;z-index:100;text-align:right';
  document.body.appendChild(hud);

  app.ticker.add(() => {
    const spd = 3;
    if (keys['KeyA'] || keys['ArrowLeft']) player.x -= spd;
    if (keys['KeyD'] || keys['ArrowRight']) player.x += spd;
    player.x = Math.max(20, Math.min(W-20, player.x));

    bullets.forEach((b, i) => { b.y += b.vy; if(b.y < -10) { b.visible = false; } });

    enemies.forEach(e => {
      e.x += e.vx;
      bullets.forEach(b => {
        if (b.visible && Math.abs(b.x-e.x)<15 && Math.abs(b.y-e.y)<20) {
          b.visible = false; e.hp--;
          if (e.hp <= 0) { e.visible = false; kills++; score += 100 * wave; document.getElementById('score').textContent = score; }
        }
      });
      if (Math.abs(e.x - player.x) < 20 && Math.abs(e.y - player.y) < 30) {
        hp -= 10; e.visible = false;
      }
    });

    hud.textContent = `HP: ${hp} | AMMO: ${ammo} | WAVE: ${wave} | KILLS: ${kills}`;
  });

  console.log('[SLA113] Tactical FPS initialized');
})();
"""


def _platformer_template(game_name, game_type, config_json, manifest_json, assets):
    return _header(game_name, game_type, config_json, manifest_json) + """(async () => {
  const app = new PIXI.Application({ width: window.innerWidth, height: window.innerHeight, backgroundColor: 0x101828, antialias: true });
  document.body.appendChild(app.view);
  document.getElementById('loading').style.display = 'none';
  window.addEventListener('resize', () => app.renderer.resize(window.innerWidth, window.innerHeight));

  const W = app.screen.width, H = app.screen.height;
  let score = 0, coins = 0;
  const keys = {}, G = 0.5;
  document.addEventListener('keydown', e => keys[e.code] = true);
  document.addEventListener('keyup', e => keys[e.code] = false);

  // Platforms
  const platforms = [];
  const platformData = [
    { x: 0, y: H-40, w: W, h: 40 },
    { x: 200, y: H-160, w: 200, h: 20 },
    { x: 500, y: H-280, w: 180, h: 20 },
    { x: 100, y: H-380, w: 150, h: 20 },
    { x: 700, y: H-200, w: 220, h: 20 },
    { x: 400, y: H-440, w: 160, h: 20 },
    { x: 900, y: H-340, w: 200, h: 20 },
  ];
  platformData.forEach(p => {
    const g = new PIXI.Graphics();
    g.beginFill(0x2a2a2a).drawRect(0, 0, p.w, p.h).endFill();
    g.lineStyle(1, 0x444444).drawRect(0, 0, p.w, p.h);
    g.x = p.x; g.y = p.y;
    g.pw = p.w; g.ph = p.h;
    app.stage.addChild(g); platforms.push(g);
  });

  // Coins
  const coinList = [];
  for (let i = 0; i < 8; i++) {
    const c = new PIXI.Graphics();
    c.beginFill(0xd4af37).drawCircle(0, 0, 8).endFill();
    c.beginFill(0xf0d060).drawCircle(0, 0, 5).endFill();
    c.x = 150 + Math.random() * (W-300); c.y = H - 100 - Math.random() * 400;
    c.collected = false;
    app.stage.addChild(c); coinList.push(c);
  }

  // Player
  const player = new PIXI.Graphics();
  player.beginFill(0x00c8ff).drawRect(-12, -20, 24, 40).endFill();
  player.x = 80; player.y = H - 80; player.vx = 0; player.vy = 0; player.grounded = false;
  app.stage.addChild(player);

  app.ticker.add(() => {
    if (keys['KeyA'] || keys['ArrowLeft']) player.vx = -4;
    else if (keys['KeyD'] || keys['ArrowRight']) player.vx = 4;
    else player.vx *= 0.85;
    if ((keys['KeyW'] || keys['ArrowUp'] || keys['Space']) && player.grounded) { player.vy = -12; player.grounded = false; }

    player.vy += G;
    player.x += player.vx; player.y += player.vy;
    player.grounded = false;

    platforms.forEach(p => {
      if (player.x+12>p.x && player.x-12<p.x+p.pw && player.y+20>p.y && player.y+20<p.y+p.ph+10 && player.vy>=0) {
        player.y = p.y - 20; player.vy = 0; player.grounded = true;
      }
    });

    if (player.x < 12) player.x = 12;
    if (player.x > W-12) player.x = W-12;
    if (player.y > H+50) { player.x = 80; player.y = H-80; player.vy = 0; }

    coinList.forEach(c => {
      if (!c.collected && Math.abs(player.x-c.x)<16 && Math.abs(player.y-c.y)<24) {
        c.collected = true; c.visible = false; coins++; score += 100;
        document.getElementById('score').textContent = score;
      }
      if (!c.collected) c.y += Math.sin(Date.now()/300 + c.x) * 0.3;
    });
  });

  console.log('[SLA113] Platformer initialized');
})();
"""


def _rpg_template(game_name, game_type, config_json, manifest_json, assets):
    return _header(game_name, game_type, config_json, manifest_json) + """(async () => {
  const app = new PIXI.Application({ width: window.innerWidth, height: window.innerHeight, backgroundColor: 0x0a0a12, antialias: true });
  document.body.appendChild(app.view);
  document.getElementById('loading').style.display = 'none';
  window.addEventListener('resize', () => app.renderer.resize(window.innerWidth, window.innerHeight));

  const W = app.screen.width, H = app.screen.height;
  let score = 0, hp = 100, xp = 0, level = 1;
  const keys = {};
  document.addEventListener('keydown', e => keys[e.code] = true);
  document.addEventListener('keyup', e => keys[e.code] = false);

  // Tile grid
  const tileSize = 32;
  for (let x = 0; x < W; x += tileSize) {
    for (let y = 0; y < H; y += tileSize) {
      const t = new PIXI.Graphics();
      const shade = 0x0a0a12 + (((x+y)/tileSize)%2 ? 0x020204 : 0);
      t.beginFill(shade).drawRect(x, y, tileSize, tileSize).endFill();
      t.lineStyle(1, 0x151520).drawRect(x, y, tileSize, tileSize);
      app.stage.addChild(t);
    }
  }

  // Player
  const player = new PIXI.Graphics();
  player.beginFill(0x00c8ff).drawRect(-12, -12, 24, 24).endFill();
  player.beginFill(0xd4af37).drawRect(-4, -16, 8, 6).endFill(); // crown
  player.x = W/2; player.y = H/2;
  app.stage.addChild(player);

  // Monsters
  const monsters = [];
  function spawnMonster() {
    const m = new PIXI.Graphics();
    const color = [0xff4444, 0x9966ff, 0xff6600, 0xcc0033][Math.floor(Math.random()*4)];
    m.beginFill(color).drawRect(-10,-10,20,20).endFill();
    m.beginFill(0xffffff).drawCircle(-3,-3,2).drawCircle(5,-3,2).endFill();
    m.x = Math.random()*W; m.y = Math.random()*H;
    m.hp = level + Math.floor(Math.random()*3);
    m.speed = 0.3 + Math.random()*0.5;
    m.xpValue = 10 + level * 5;
    m.interactive = true; m.cursor = 'pointer';
    m.on('pointerdown', () => {
      m.hp -= 5 + level * 2;
      m.alpha = 0.5; setTimeout(()=>m.alpha=0.9, 100);
      if (m.hp <= 0) {
        m.visible = false; xp += m.xpValue; score += m.xpValue;
        if (xp >= level * 100) { level++; xp = 0; hp = Math.min(hp+20,100); }
        document.getElementById('score').textContent = `LV${level} XP:${xp}`;
      }
    });
    app.stage.addChild(m); monsters.push(m);
  }
  for (let i = 0; i < 6; i++) spawnMonster();
  setInterval(spawnMonster, 4000);

  const hud = document.createElement('div');
  hud.style.cssText = 'position:fixed;bottom:16px;left:16px;color:#9966ff;font:11px monospace;text-transform:uppercase;letter-spacing:2px;z-index:100';
  document.body.appendChild(hud);

  app.ticker.add(() => {
    const spd = 3;
    if (keys['KeyW']||keys['ArrowUp']) player.y -= spd;
    if (keys['KeyS']||keys['ArrowDown']) player.y += spd;
    if (keys['KeyA']||keys['ArrowLeft']) player.x -= spd;
    if (keys['KeyD']||keys['ArrowRight']) player.x += spd;
    player.x = Math.max(12,Math.min(W-12,player.x));
    player.y = Math.max(12,Math.min(H-12,player.y));

    monsters.forEach(m => {
      if (!m.visible) return;
      const dx = player.x-m.x, dy = player.y-m.y, d = Math.sqrt(dx*dx+dy*dy);
      if (d > 0) { m.x += dx/d*m.speed; m.y += dy/d*m.speed; }
      if (d < 18) { hp -= 0.2; }
    });

    hud.textContent = `HP: ${Math.floor(hp)} | LV: ${level} | XP: ${xp}/${level*100} | SCORE: ${score}`;
  });

  console.log('[SLA113] RPG initialized');
})();
"""


def _racing_template(game_name, game_type, config_json, manifest_json, assets):
    return _header(game_name, game_type, config_json, manifest_json) + """(async () => {
  const app = new PIXI.Application({ width: window.innerWidth, height: window.innerHeight, backgroundColor: 0x2d5a27, antialias: true });
  document.body.appendChild(app.view);
  document.getElementById('loading').style.display = 'none';
  window.addEventListener('resize', () => app.renderer.resize(window.innerWidth, window.innerHeight));

  const W = app.screen.width, H = app.screen.height;
  let score = 0, speed = 0, lap = 0;
  const keys = {};
  document.addEventListener('keydown', e => keys[e.code] = true);
  document.addEventListener('keyup', e => keys[e.code] = false);

  // Road
  const road = new PIXI.Graphics();
  road.beginFill(0x333333).drawRect(W/2-150, 0, 300, H).endFill();
  road.lineStyle(2, 0xffffff, 0.3);
  for (let y = 0; y < H; y += 40) road.drawRect(W/2-2, y, 4, 20);
  app.stage.addChild(road);

  // Player car
  const car = new PIXI.Graphics();
  car.beginFill(0x00c8ff).drawRoundedRect(-15, -25, 30, 50, 4).endFill();
  car.beginFill(0x006688).drawRect(-12, -15, 24, 30).endFill();
  car.beginFill(0xff0000).drawRect(-10, 20, 8, 5).drawRect(2, 20, 8, 5).endFill();
  car.x = W/2; car.y = H - 100;
  app.stage.addChild(car);

  // Obstacles
  const obstacles = [];
  setInterval(() => {
    const o = new PIXI.Graphics();
    o.beginFill(0xff4444).drawRoundedRect(-12, -20, 24, 40, 3).endFill();
    o.x = W/2 - 120 + Math.random() * 240; o.y = -40;
    o.speed = 2 + speed * 0.1 + Math.random() * 2;
    app.stage.addChild(o); obstacles.push(o);
  }, 1500);

  app.ticker.add(() => {
    if (keys['KeyA']||keys['ArrowLeft']) car.x -= 4;
    if (keys['KeyD']||keys['ArrowRight']) car.x += 4;
    if (keys['KeyW']||keys['ArrowUp']) speed = Math.min(speed+0.1, 10);
    else speed = Math.max(speed-0.05, 1);
    car.x = Math.max(W/2-130, Math.min(W/2+130, car.x));

    obstacles.forEach(o => {
      o.y += o.speed + speed;
      if (o.y > H+50) { o.visible = false; score += 10; }
      if (o.visible && Math.abs(o.x-car.x)<22 && Math.abs(o.y-car.y)<35) {
        speed = 0; o.visible = false;
      }
    });

    score += Math.floor(speed * 0.1);
    document.getElementById('score').textContent = score;
  });

  console.log('[SLA113] Racing Sim initialized');
})();
"""


def _open_world_template(game_name, game_type, config_json, manifest_json, assets):
    return _rpg_template(game_name, game_type, config_json, manifest_json, assets)


def _horror_template(game_name, game_type, config_json, manifest_json, assets):
    return _rpg_template(game_name, game_type, config_json, manifest_json, assets)


def _fighting_template(game_name, game_type, config_json, manifest_json, assets):
    return _tactical_fps_template(game_name, game_type, config_json, manifest_json, assets)


def _puzzle_template(game_name, game_type, config_json, manifest_json, assets):
    return _platformer_template(game_name, game_type, config_json, manifest_json, assets)


def _video_poker_template(game_name, game_type, config_json, manifest_json, assets):
    return _slot_machine_template(game_name, game_type, config_json, manifest_json, assets)


def _default_template(game_name, game_type, config_json, manifest_json, assets):
    """Default generic template with interactive entities."""
    return _header(game_name, game_type, config_json, manifest_json) + (
        "(async () => {\n"
        "  const app = new PIXI.Application({ width: window.innerWidth, height: window.innerHeight, backgroundColor: 0x0a0a0a, antialias: true });\n"
        "  document.body.appendChild(app.view);\n"
        "  document.getElementById('loading').style.display = 'none';\n"
        "  window.addEventListener('resize', () => { app.renderer.resize(window.innerWidth, window.innerHeight); });\n\n"
        "  let score = 0;\n"
        "  let entities = [];\n"
        "  const W = app.screen.width, H = app.screen.height;\n\n"
        "  const grid = new PIXI.Graphics();\n"
        "  grid.lineStyle(1, 0x111111);\n"
        "  for (let x = 0; x < W; x += 40) grid.moveTo(x, 0).lineTo(x, H);\n"
        "  for (let y = 0; y < H; y += 40) grid.moveTo(0, y).lineTo(W, y);\n"
        "  app.stage.addChild(grid);\n\n"
        "  function spawnEntity(x, y) {\n"
        "    const g = new PIXI.Graphics();\n"
        "    const size = 20 + Math.random() * 20;\n"
        "    const colors = [0x00c8ff, 0xd4af37, 0xff4444, 0x44ff44, 0x9966ff, 0xff6600];\n"
        "    const color = colors[Math.floor(Math.random() * colors.length)];\n"
        "    g.beginFill(color, 0.8).drawRoundedRect(-size/2, -size/2, size, size, 4).endFill();\n"
        "    g.x = x; g.y = y;\n"
        "    g.vx = (Math.random() - 0.5) * 2;\n"
        "    g.vy = (Math.random() - 0.5) * 2;\n"
        "    g.interactive = true; g.cursor = 'pointer';\n"
        "    g.on('pointerdown', () => { score += 100; document.getElementById('score').textContent = score; g.alpha = 0.3; setTimeout(() => { g.alpha = 0.8; }, 300); });\n"
        "    app.stage.addChild(g); entities.push(g);\n"
        "  }\n\n"
        "  for (let i = 0; i < 16; i++) spawnEntity(Math.random()*W*0.7+W*0.15, Math.random()*H*0.7+H*0.15);\n\n"
        "  app.ticker.add(() => {\n"
        "    entities.forEach(e => {\n"
        "      e.x += e.vx; e.y += e.vy;\n"
        "      if (e.x < 20 || e.x > W-20) e.vx *= -1;\n"
        "      if (e.y < 20 || e.y > H-20) e.vy *= -1;\n"
        "      e.rotation += 0.005;\n"
        "    });\n"
        "  });\n\n"
        "  console.log('[SLA113] Game initialized');\n"
        "})();\n"
    )
