"""Developer persona: applies minimal patch within allowed paths."""
from __future__ import annotations

import json
import logging
import re
from pathlib import Path
from typing import Any, Dict, List, Tuple

from omni_agent.guardrails import Guardrails, GuardrailViolation
from omni_agent.llm_client import LLMClient, LLMUnavailable


logger = logging.getLogger("omni_agent.developer")


SYSTEM_PROMPT = (
    "You are the Developer persona inside an Omni-Agent. "
    "You receive a mini-spec and must produce a strict JSON patch object. "
    "JSON shape: {\"changes\": [{\"path\": \"<relative path>\", \"action\": \"create|append|replace\", "
    "\"content\": \"<full file content for create/replace, or text-to-append for append>\", "
    "\"summary\": \"<one-line>\"}], \"notes\": \"<optional>\"}. "
    "Only emit paths that fall under the allowed_paths list provided. "
    "Never touch forbidden paths. Output JSON only, no prose."
)


# ---------- rule-based templates ----------

_BACKEND_SVC_TPL = '''"""{module_doc}"""
from __future__ import annotations

from typing import Dict


def {func_name}() -> Dict[str, object]:
    """Auto-generated by omni-agent (rule mode) for task {task_id}."""
    return {{"status": "ok", "module": "{module_name}"}}
'''

_BACKEND_CORE_TPL = '''"""{module_doc}"""
from __future__ import annotations


def {func_name}(value: str) -> bool:
    """Auto-generated helper for task {task_id}. Replace with real logic."""
    return bool(value and value.strip())
'''

_DOCS_APPEND_TPL = "\n\n## {heading}\n\n{body}\n"


def _slug(text: str) -> str:
    s = re.sub(r"[^A-Za-z0-9]+", "_", text).strip("_").lower()
    return s[:40] or "module"


def _pick_target_path(spec: Dict[str, Any], task: Dict[str, Any], guardrails: Guardrails) -> Tuple[str, str]:
    """Returns (path, kind) where kind in {service, core, docs, generic}."""
    impacted = spec.get("impacted_files") or []
    for p in impacted:
        if "<" in p or ">" in p:
            continue
        ok, _ = guardrails.check_write(p)
        if ok:
            if p.startswith("backend/app/services/"):
                return p, "service"
            if p.startswith("backend/app/core/"):
                return p, "core"
            if p.endswith(".md"):
                return p, "docs"
            return p, "generic"

    # derive from task text
    text = task.get("normalized_text", "")
    slug = _slug(text)
    return f"backend/app/services/{slug}_service.py", "service"


def _rule_based_patch(spec: Dict[str, Any], task: Dict[str, Any], guardrails: Guardrails) -> Dict[str, Any]:
    target, kind = _pick_target_path(spec, task, guardrails)
    ok, msg = guardrails.check_write(target)
    if not ok:
        return {
            "changes": [],
            "notes": f"blocked: target '{target}' not writable ({msg})",
            "blocked": True,
        }

    slug = _slug(Path(target).stem)
    func = f"get_{slug}" if not slug.startswith("get_") else slug
    if kind == "service":
        content = _BACKEND_SVC_TPL.format(
            module_doc=f"Auto-generated service stub for task {task['id']}.",
            func_name=func,
            module_name=slug,
            task_id=task["id"],
        )
        action = "create"
    elif kind == "core":
        content = _BACKEND_CORE_TPL.format(
            module_doc=f"Auto-generated core helper for task {task['id']}.",
            func_name=func,
            task_id=task["id"],
        )
        action = "create"
    elif kind == "docs":
        content = _DOCS_APPEND_TPL.format(
            heading=f"Task {task['id']}",
            body=task["normalized_text"],
        )
        action = "append"
    else:
        content = f"# Stub for {task['id']}\n# {task['normalized_text']}\n"
        action = "create"

    return {
        "changes": [
            {
                "path": target,
                "action": action,
                "content": content,
                "summary": f"{action} {target} for {task['id']}",
            }
        ],
        "notes": f"rule-based stub generated ({kind})",
        "blocked": False,
    }


def _apply_changes(
    repo_root: Path,
    changes: List[Dict[str, Any]],
    guardrails: Guardrails,
    *,
    dry_run: bool,
) -> Tuple[List[Dict[str, Any]], List[str]]:
    applied: List[Dict[str, Any]] = []
    errors: List[str] = []
    for ch in changes:
        path = ch.get("path")
        action = ch.get("action", "create")
        content = ch.get("content", "")
        if not path or not isinstance(content, str):
            errors.append(f"invalid change entry: {ch}")
            continue
        ok, msg = guardrails.check_write(path)
        if not ok:
            errors.append(f"guardrail blocked '{path}': {msg}")
            continue
        full = repo_root / path
        result_entry = {"path": path, "action": action, "summary": ch.get("summary", "")}
        if dry_run:
            result_entry["dry_run"] = True
            applied.append(result_entry)
            continue
        try:
            full.parent.mkdir(parents=True, exist_ok=True)
            if action == "append" and full.exists():
                with full.open("a", encoding="utf-8") as f:
                    f.write(content)
            else:
                full.write_text(content, encoding="utf-8")
            applied.append(result_entry)
        except OSError as e:
            errors.append(f"write failed '{path}': {e}")
    return applied, errors


def run(
    task: Dict[str, Any],
    triage: Dict[str, Any],
    spec: Dict[str, Any],
    llm: LLMClient,
    guardrails: Guardrails,
    repo_root: Path,
    persona_mode: str,
    dry_run: bool,
) -> Dict[str, Any]:
    patch = None
    mode_used = "rule"

    if persona_mode in ("llm", "hybrid"):
        try:
            payload = {
                "task": {"id": task["id"], "text": task["normalized_text"]},
                "triage": triage,
                "spec": spec,
                "allowed_paths": guardrails.allowed,
                "forbidden_paths": guardrails.forbidden,
            }
            res = llm.call(
                SYSTEM_PROMPT,
                "Spec payload:\n" + json.dumps(payload, indent=2),
                session_id=f"developer-{task['id']}",
            )
            parsed = LLMClient.extract_json(res.text)
            if parsed and isinstance(parsed.get("changes"), list):
                # filter unsafe paths
                safe_changes = []
                filtered_paths: List[str] = []
                for ch in parsed["changes"]:
                    p = ch.get("path", "")
                    ok, reason = guardrails.check_write(p)
                    if ok:
                        safe_changes.append(ch)
                    else:
                        filtered_paths.append(p)
                        logger.info("developer: filtered out-of-allowlist path '%s' (%s)", p, reason)
                if safe_changes:
                    patch = {
                        "changes": safe_changes,
                        "notes": parsed.get("notes", ""),
                        "blocked": False,
                        "filtered_paths": filtered_paths,
                        "proposed_total": len(parsed["changes"]),
                    }
                    mode_used = "llm"
        except LLMUnavailable as e:
            if persona_mode == "llm":
                raise
            logger.info("developer: LLM unavailable (%s); falling back to rule mode", e)

    if patch is None:
        patch = _rule_based_patch(spec, task, guardrails)

    if patch.get("blocked"):
        return {
            "patch": patch,
            "applied": [],
            "errors": [],
            "mode_used": mode_used,
            "blocked_context": patch.get("notes", "no writable target inferred"),
        }

    applied, errors = _apply_changes(repo_root, patch["changes"], guardrails, dry_run=dry_run)
    return {
        "patch": patch,
        "applied": applied,
        "errors": errors,
        "mode_used": mode_used,
        "blocked_context": None,
        "filtered_paths": patch.get("filtered_paths", []),
        "proposed_total": patch.get("proposed_total", len(patch.get("changes", []))),
    }
