/**
 * DemoScene.js
 *
 * Proves the whole pipeline end-to-end: loads atlases -> builds animations ->
 * spawns minions patrolling the tank -> spawns a rotating cast of bosses with
 * a health bar -> wires a player cannon that fires projectiles -> projectiles
 * hit entities -> hits trigger 'hit' animation + enrage threshold + impact FX
 * -> kills trigger 'death' animation + coin FX + respawn (minions only) ->
 * kill streaks build a combo that upgrades the cannon's shot type.
 *
 * This is the honest "does the system work" harness. It uses the placeholder
 * atlases generated by tools/pack_atlas.py. Swapping in real art later means
 * regenerating/replacing the same-named atlas files — nothing in this scene
 * changes.
 */

import { queueAssetLoad, buildAllAnimations } from './AssetLoader.js';
import { listMinionIds, listBossIds, listTreasureIds, getCreature } from './CreatureRegistry.js';
import { CombatEntity } from './CombatEntity.js';
import { BossHealthBar } from './BossHealthBar.js';
import { CannonController } from './CannonController.js';
import { ProjectileManager } from './ProjectileManager.js';
import { ImpactFxManager, CoinFxManager } from './FxManagers.js';

const ARENA_WIDTH = 800;
const ARENA_HEIGHT = 600;
const MINION_COUNT = 6;
const MINION_Y_MIN = 60;
const MINION_Y_MAX = 300;
const TREASURE_Y_MIN = 340;
const TREASURE_Y_MAX = 560;
const TREASURE_LIFETIME_MS = 6000;
const COMBO_WINDOW_MS = 1500;
const COMBO_HARPOON_THRESHOLD = 3;
const COMBO_MAX_MULTIPLIER = 5;
const WAVE_STAT_STEP = 0.18; // +18% health/speed per wave, health uncapped, speed capped below
const WAVE_SPEED_CAP_MULT = 1.6;
const SAVE_KEY = 'sla113_totalCoins';
const HUD_STYLE = { fontFamily: 'JetBrains Mono, monospace', fontSize: '16px', color: '#c9a227' };

export class DemoScene extends Phaser.Scene {
  constructor() {
    super('DemoScene');
    this.entities = [];
  }

  preload() {
    queueAssetLoad(this);
  }

  create() {
    this.cameras.main.setBackgroundColor('#050505');
    buildAllAnimations(this);

    this.wave = 1;
    this.totalCoins = Number(localStorage.getItem(SAVE_KEY)) || 0;
    this.comboCount = 0;
    this.comboResetEvent = null;
    this.bossRotation = listBossIds();

    this._spawnMinions();
    this._spawnBoss(0);
    this._scheduleTreasureSpawn();

    this.projectileManager = new ProjectileManager(this, { speed: 700, damage: 6 });
    this.impactFx = new ImpactFxManager(this);
    this.coinFx = new CoinFxManager(this);

    this.projectileManager.setTargets(this.entities.map(e => e.entity));
    this.projectileManager.onHitTarget = (entity, bullet) => {
      this.impactFx.playAt(bullet.x, bullet.y);
    };

    this.cannon = new CannonController(
      this, ARENA_WIDTH / 2, ARENA_HEIGHT - 40, this.projectileManager,
      { getProjectileType: () => (this.comboCount >= COMBO_HARPOON_THRESHOLD ? 'harpoon' : 'bolt') }
    );

    this._addHud();
  }

  update(time, delta) {
    this.projectileManager.update();
    for (const wrapped of this.entities) {
      if (!wrapped.entity.isDead) this._patrol(wrapped, delta);
    }
  }

  // ---- difficulty scaling --------------------------------------------------

  _statsForWave(cfg) {
    const mult = 1 + (this.wave - 1) * WAVE_STAT_STEP;
    return {
      health: Math.round(cfg.baseHealth * mult),
      speed: cfg.baseSpeed * Math.min(mult, WAVE_SPEED_CAP_MULT),
    };
  }

  // ---- minions --------------------------------------------------------------

  _spawnMinions() {
    const minionIds = listMinionIds();
    for (let i = 0; i < MINION_COUNT; i++) {
      this._createMinion(minionIds[i % minionIds.length]);
    }
  }

  _createMinion(creatureId) {
    const cfg = getCreature(creatureId);
    const x = Phaser.Math.Between(60, ARENA_WIDTH - 60);
    const y = Phaser.Math.Between(MINION_Y_MIN, MINION_Y_MAX);
    const entity = new CombatEntity(this, creatureId, x, y, this._statsForWave(cfg));
    entity.playState('swim');

    entity.onDeath = (deadEntity) => {
      this._registerKill();
      const mult = this._currentComboMultiplier();
      this.coinFx.playAt(deadEntity.sprite.x, deadEntity.sprite.y, cfg.baseCoinValue, mult);
      this._addCoins(cfg.baseCoinValue * mult);
      this.time.delayedCall(1500, () => this._respawnMinion(deadEntity));
    };

    this.entities.push({
      entity,
      dir: Phaser.Math.FloatBetween(0, Math.PI * 2),
      turnTimer: 0,
    });
    this._scheduleMinionAttack(entity);
  }

  _respawnMinion(deadEntity) {
    if (!this.entities.some(w => w.entity === deadEntity)) return;
    this._removeEntity(deadEntity);

    const minionIds = listMinionIds();
    const creatureId = minionIds[Phaser.Math.Between(0, minionIds.length - 1)];
    this._createMinion(creatureId);
  }

  /** Minions periodically windup an attack, purely to prove hit-during-attack
   *  queueing works for more than just the boss. Self-terminating: a dead
   *  entity is simply never rescheduled. */
  _scheduleMinionAttack(entity) {
    const delay = Phaser.Math.Between(3500, 7000);
    this.time.delayedCall(delay, () => {
      if (entity.isDead) return;
      entity.attack();
      this._scheduleMinionAttack(entity);
    });
  }

  // ---- boss rotation ----------------------------------------------------

  _spawnBoss(bossIndex) {
    const bossIds = this.bossRotation;
    if (!bossIds || bossIds.length === 0) return;

    const bossId = bossIds[bossIndex % bossIds.length];
    const cfg = getCreature(bossId);
    const boss = new CombatEntity(this, bossId, ARENA_WIDTH / 2, 130, this._statsForWave(cfg));
    boss.playState('idle');

    boss.onDeath = (deadBoss) => {
      this._registerKill();
      const mult = this._currentComboMultiplier();
      this.coinFx.playAt(deadBoss.sprite.x, deadBoss.sprite.y, cfg.baseCoinValue, mult);
      this._addCoins(cfg.baseCoinValue * mult);

      if (this.bossAttackTimer) this.bossAttackTimer.remove(false);
      if (this.bossHealthBar) {
        this.bossHealthBar.destroy();
        this.bossHealthBar = null;
      }
      this._removeEntity(deadBoss);

      this.wave++;
      this._updateWaveHud();
      this.time.delayedCall(2500, () => this._spawnBoss(bossIndex + 1));
    };

    this.entities.push({ entity: boss, dir: 0, turnTimer: 0, isBoss: true });
    this.bossHealthBar = new BossHealthBar(this, boss, { x: ARENA_WIDTH / 2, y: 40, width: 420 });

    if (this.projectileManager) this.projectileManager.setTargets(this.entities.map(e => e.entity));

    // Periodic boss attack animation just to prove attack windup doesn't
    // conflict with incoming hit reactions (see CombatEntity's queue rule).
    this.bossAttackTimer = this.time.addEvent({
      delay: 3000,
      loop: true,
      callback: () => { if (!boss.isDead) boss.attack(); },
    });
  }

  // ---- treasure (flees instead of fighting) --------------------------------

  _scheduleTreasureSpawn() {
    const delay = Phaser.Math.Between(10000, 16000);
    this.time.delayedCall(delay, () => {
      this._spawnTreasure();
      this._scheduleTreasureSpawn();
    });
  }

  _spawnTreasure() {
    const treasureIds = listTreasureIds();
    if (treasureIds.length === 0) return;

    const creatureId = treasureIds[Phaser.Math.Between(0, treasureIds.length - 1)];
    const cfg = getCreature(creatureId);
    const x = Phaser.Math.Between(60, ARENA_WIDTH - 60);
    const y = Phaser.Math.Between(TREASURE_Y_MIN, TREASURE_Y_MAX);
    const entity = new CombatEntity(this, creatureId, x, y, this._statsForWave(cfg));
    entity.playState('swim');

    entity.onDeath = (deadEntity) => {
      this._registerKill();
      const mult = this._currentComboMultiplier();
      this.coinFx.playAt(deadEntity.sprite.x, deadEntity.sprite.y, cfg.baseCoinValue, mult);
      this._addCoins(cfg.baseCoinValue * mult);
      this._removeEntity(deadEntity);
    };

    this.entities.push({ entity, dir: 0, turnTimer: 0, isTreasure: true });
    this.projectileManager.setTargets(this.entities.map(e => e.entity));

    // Got away — fade out and despawn rather than lingering forever.
    this.time.delayedCall(TREASURE_LIFETIME_MS, () => {
      if (entity.isDead) return;
      this.tweens.add({
        targets: entity.sprite,
        alpha: 0,
        duration: 400,
        onComplete: () => this._removeEntity(entity),
      });
    });
  }

  // ---- shared entity lifecycle --------------------------------------------

  _removeEntity(entity) {
    const idx = this.entities.findIndex(w => w.entity === entity);
    if (idx !== -1) this.entities.splice(idx, 1);
    entity.destroy();
    this.projectileManager.setTargets(this.entities.map(e => e.entity));
  }

  // ---- combo multiplier -----------------------------------------------------

  _registerKill() {
    this.comboCount++;
    if (this.comboResetEvent) this.comboResetEvent.remove(false);
    this.comboResetEvent = this.time.delayedCall(COMBO_WINDOW_MS, () => {
      this.comboCount = 0;
      this._updateComboHud();
    });
    this._updateComboHud();
  }

  _currentComboMultiplier() {
    return Math.max(1, Math.min(this.comboCount, COMBO_MAX_MULTIPLIER));
  }

  // ---- score persistence -----------------------------------------------------

  _addCoins(value) {
    this.totalCoins += value;
    localStorage.setItem(SAVE_KEY, String(this.totalCoins));
    this._updateScoreHud();
  }

  // ---- movement / patrol -----------------------------------------------------

  _patrol(wrapped, delta) {
    const { entity } = wrapped;
    if (wrapped.isBoss) return; // boss holds position, doesn't patrol

    const cfg = getCreature(entity.creatureId);
    wrapped.turnTimer -= delta;
    if (wrapped.turnTimer <= 0) {
      wrapped.dir += Phaser.Math.FloatBetween(-1, 1);
      wrapped.turnTimer = Phaser.Math.Between(800, 2000);
    }

    if (cfg.movement === 'flee') {
      this._patrolFlee(wrapped);
    } else if (cfg.movement === 'weave') {
      this._patrolWeave(wrapped, delta);
    } else {
      this._patrolDrift(wrapped);
    }
  }

  _patrolDrift(wrapped) {
    const { entity } = wrapped;
    const vx = Math.cos(wrapped.dir) * entity.speed;
    const vy = Math.sin(wrapped.dir) * entity.speed * 0.4; // flatten vertical drift
    entity.sprite.body.setVelocity(vx, vy);
    entity.sprite.setFlipX(vx < 0);

    // Soft bounds so minions stay in the swim lane
    if (entity.sprite.x < 40 || entity.sprite.x > ARENA_WIDTH - 40) wrapped.dir = Math.PI - wrapped.dir;
    if (entity.sprite.y < 40 || entity.sprite.y > MINION_Y_MAX + 20) wrapped.dir = -wrapped.dir;
  }

  /** Flyers weave a pronounced sine wave vertically while drifting horizontally. */
  _patrolWeave(wrapped, delta) {
    const { entity } = wrapped;
    wrapped.weavePhase = (wrapped.weavePhase || 0) + delta * 0.004;
    const vx = Math.cos(wrapped.dir) * entity.speed;
    const vy = Math.sin(wrapped.weavePhase) * entity.speed * 0.9;
    entity.sprite.body.setVelocity(vx, vy);
    entity.sprite.setFlipX(vx < 0);

    if (entity.sprite.x < 40 || entity.sprite.x > ARENA_WIDTH - 40) wrapped.dir = Math.PI - wrapped.dir;
    entity.sprite.y = Phaser.Math.Clamp(entity.sprite.y, 40, MINION_Y_MAX);
  }

  /** Treasure creatures run away from the cannon's current aim point. */
  _patrolFlee(wrapped) {
    const { entity } = wrapped;
    const pointer = this.input.activePointer;
    const angle = (pointer && (pointer.x || pointer.y))
      ? Phaser.Math.Angle.Between(pointer.x, pointer.y, entity.sprite.x, entity.sprite.y)
      : wrapped.dir;

    const vx = Math.cos(angle) * entity.speed;
    const vy = Math.sin(angle) * entity.speed;
    entity.sprite.body.setVelocity(vx, vy);
    entity.sprite.setFlipX(vx < 0);

    entity.sprite.x = Phaser.Math.Clamp(entity.sprite.x, 40, ARENA_WIDTH - 40);
    entity.sprite.y = Phaser.Math.Clamp(entity.sprite.y, TREASURE_Y_MIN, TREASURE_Y_MAX);
  }

  // ---- HUD --------------------------------------------------------------

  _addHud() {
    this.scoreText = this.add.text(12, 12, `Coins: ${this.totalCoins}`, HUD_STYLE);
    this.comboText = this.add.text(12, 34, '', { ...HUD_STYLE, fontSize: '14px', color: '#ff8844' });
    this.waveText = this.add.text(ARENA_WIDTH - 12, 12, `Wave ${this.wave}`, HUD_STYLE).setOrigin(1, 0);

    this.add.text(12, ARENA_HEIGHT - 26,
      'Click/tap to fire  •  combo x3 upgrades to harpoon  •  Placeholder art — swap assets/atlases/*.png to use real frames',
      { fontFamily: 'JetBrains Mono, monospace', fontSize: '12px', color: '#666666' }
    );
  }

  _updateScoreHud() {
    if (this.scoreText) this.scoreText.setText(`Coins: ${this.totalCoins}`);
  }

  _updateComboHud() {
    if (this.comboText) {
      this.comboText.setText(this.comboCount > 1 ? `Combo x${this._currentComboMultiplier()}` : '');
    }
  }

  _updateWaveHud() {
    if (this.waveText) this.waveText.setText(`Wave ${this.wave}`);
  }
}
